name : silkspawnerPlugin
version: 1.0
description: a small plugin that allows the player to retrieve a spawner using a diamond or iron pickaxe with the silktouch enchantment !
author: theobessel

main: fr.theobessel.silkspawner.pluginLoader

commands: